### ISSUE TITLE
VISA fixed but...

### ISSUE THREAD

**Issue by Samuelincoom** [norrisboat/SlydepayAndroidREST#1]
indeed, The VISACARD option was fixed but, now opens a webview that is not responsive...  when you select "im a test user" and enter your email, upon clicking "PAY", nothing happens...  Your webview page is just static...

PS: ( Maybe the unresponsive webview i see is as a result of my duckduckgo browser.. unfortunately i can never trust Google services and i try to use anything "Google" as little as possible, after some personal experience i had with their services, so if you are one of the billions of people that trust Google's services, i would really appreaciate it if you use your Google chrome browser to confirm whether the problem is really from my browser...  thank you..
  I use the DUCKDUCKGO browser by default to open any webview material on my phone, because i am a bit paranoid and not comfortable with Google's stalking activities through android devices and their chrome browser...  There are confirmed reports in leaked CIA documents by the Wikileaks VAULT 7 released last year here https://wikileaks.org/ciav7p1/cms/index.html  of this EXTREME Google stalking and a back channel of Google's data to the pentagon's database, Meaning this Google company ordinary people trust so much, is really just a pawn for the US government deepstate or CIA and your Data is never safe with them...
 )

**Comment by Samuelincoom** [comment]
You dont worry, i will try it on a Google Chrome browser with a friend's phone tonight

**Comment by norrisboat** [comment]
@Samuelincoom I'm not in the slydepay team so can't optimize the webview to be responsive. I just made a wrapper around their REST SDK but will forward it to someone on the team if its still an issue.
PS:  Never knew about the wikileaks thing thanks for sharing. Have kind of given up on privacy now but you have valid concerns not to use it.
If it worked let me know so I close the issue

**Comment by Samuelincoom** [comment]
I tried it on my friends phone and his Google chrome and had the same problem..   

But, You don't worry, I'm about to create a repository next week and show how to combine slydepay's SDK with Stripe's SDK..   I really think it would help other developers and entrepreneurs bypass slydepay's VISACARD challenges with out them needing to register their business in USA like Ghanaians need to do to access stripe's LIVE API..

**Comment by norrisboat** [comment]
OK. Keep me posted
